language: node_js
notifications:
  webhooks:
    urls:
      - https://cloudcite-api-build-status.herokuapp.com
node_js:
  - "8.1"
  - "lts/*"
  - "node"
env:
  global:
    - PRIVATE_REPO = true
script:
  - node cite index.js
  - node cloudfront-distribution index.js