language: node_js
notifications:
  webhooks:
      - https://cloudcite-api-build-status.herokuapp.com/webhook
node_js:
  - "8.1"
  - "lts/*"
  - "node"
env:
  global:
    - PRIVATE_REPO = true
script:
  - node cite index.js
  - node cloudfront-origin-request index.js
  - node cloudfront-origin-response index.js